In [3]:
import pandas as pd

NYapp = pd.read_csv("NY_Applicants.csv")
OutState = pd.read_csv("OutOfState.csv")
Transfers = pd.read_csv("Transfer_Applicants.csv")

In [7]:
len(NYapp)

1000

In [5]:
len(OutState)

1000

In [6]:
len(Transfers)

1000

In [8]:
all_NY_data = pd.concat([NYapp, OutState, Transfers], sort=False)

In [10]:
all_NY_data.head(10)

,Student_id,first_name,last_name,gender,street_address,city,state,email,zip,phone,GPA
0,510-80-2938,Mandel,Matthesius,Genderfluid,012 Kenwood Parkway,New York City,New York,mmatthesius0@house.gov,10120,212-946-3551,2.79
1,447-16-5664,Cloe,O'Cannan,Male,24256 Debs Hill,Albany,New York,cocannan1@bigcartel.com,12242,518-497-4604,2.32
2,689-09-5341,Sydel,Beatens,Male,4 Stang Trail,New York City,New York,sbeatens2@istockphoto.com,10120,212-659-2138,3.30
3,103-98-0262,Loralyn,Snipe,Non-binary,1541 Eagle Crest Avenue,New York City,New York,lsnipe3@nydailynews.com,10045,347-657-2183,3.02
4,169-76-2651,Harlan,Plose,Agender,48255 Farmco Junction,Rochester,New York,hplose4@state.tx.us,14652,585-948-4650,1.60
5,647-68-3042,Mal,Prestner,Genderfluid,5 Mifflin Park,New York City,New York,mprestner5@weather.com,10260,212-143-1391,3.70
6,158-21-1189,Wheeler,Ledster,Polygender,804 Waubesa Hill,Elmira,New York,wledster6@angelfire.com,14905,607-903-2744,3.55
7,896-76-9450,Anders,Sedgefield,Male,9 Hoepker Alley,New York City,New York,asedgefield7@dot.gov,10165,646-141-1835,3.49
8,885-88-1089,Leeann,Eakly,Non-binary,503 Myrtle Lane,Buffalo,New York,leakly8@etsy.com,14263,716-277-7630,3.38
9,230-50-1956,Alene,Bandey,Non-binary,33899 David Place,Bronx,New York,abandey9@seesaa.net,10454,718-478-0590,1.78
10,573-97-5473,Rex,Tweedy,Male,99 Rutledge Street,New York City,New York,rtweedya@techcrunch.com,10029,212-268-3008,1.66

In [11]:
all_NY_data.tail(10)

,Student_id,first_name,last_name,gender,street_address,city,state,email,zip,phone,GPA
990,124-05-3619,Bette-ann,Voaden,Genderfluid,7 Onsgard Alley,Albany,New York,bvoadenri@instagram.com,12242,518-133-8553,2.88
991,710-05-0062,Berti,Kenwyn,Bigender,13035 Larry Place,Bronx,New York,bkenwynrj@discovery.com,10464,914-196-7000,3.31
992,622-68-6244,Jeremias,Brunton,Genderqueer,38 Annamark Park,New York City,New York,jbruntonrk@answers.com,10039,646-708-7357,1.09
993,419-59-0712,Manya,Boddymead,Bigender,48406 Burrows Place,Buffalo,New York,mboddymeadrl@purevolume.com,14220,716-738-2812,1.31
994,113-81-7717,Dasi,Wainman,Agender,89 Artisan Plaza,Albany,New York,dwainmanrm@irs.gov,12262,518-999-8316,1.93
995,706-55-7345,Athena,Balsdon,Agender,3 Fisk Lane,Albany,New York,abalsdonrn@surveymonkey.com,12255,518-643-1046,3.75
996,870-13-4298,Jyoti,Taunton,Genderfluid,87774 Crescent Oaks Plaza,Bronx,New York,jtauntonro@cmu.edu,10464,718-251-3971,3.79
997,689-75-0688,Suzann,Derington,Genderfluid,1 Norway Maple Drive,New York City,New York,sderingtonrp@dmoz.org,10170,212-283-2734,2.14
998,560-28-3066,Chicky,Sphinxe,Male,12990 1st Terrace,Albany,New York,csphinxerq@instagram.com,12262,518-228-2505,2.33
999,223-70-4507,Herold,Flitcroft,Genderqueer,0 Elka Court,Great Neck,New York,hflitcroftrr@auda.org.au,11024,516-641-6207,3.03

In [12]:
all_NY_data["gender"].value_counts()

Polygender     399
Genderfluid    398
Non-binary     382
Agender        373
Female         368
Male           366
Genderqueer    360
Bigender       354
Name: gender, dtype: int64

In [13]:
all_NY_data.keys()

Index(['Student_id', 'first_name', 'last_name', 'gender', 'street_address',
       'city', 'state', 'email', 'zip', 'phone', 'GPA'],
      dtype='object')

In [24]:
all_data_dropped = all_NY_data.drop(['email', 'phone'], axis = 1)

In [33]:
NY = all_data_dropped[all_data_dropped['city'] == 'New York City']

In [38]:
NY['GPA'].mean()

2.499866666666669

In [39]:
Alb = all_data_dropped[all_data_dropped['city'] == 'Albany']

,Student_id,first_name,last_name,gender,street_address,city,state,zip,GPA
1,447-16-5664,Cloe,O'Cannan,Male,24256 Debs Hill,Albany,New York,12242,2.32
15,297-28-1056,Hildagard,Mapes,Female,2732 Jenna Circle,Albany,New York,12210,3.45
22,504-53-1795,Heddie,Liggens,Genderfluid,6940 Schurz Terrace,Albany,New York,12262,3.03
25,776-89-7319,Risa,Murdy,Polygender,9452 Superior Point,Albany,New York,12232,1.93
27,469-54-5189,Sallyanne,Baugham,Genderqueer,2 Pleasure Plaza,Albany,New York,12242,3.03
...,...,...,...,...,...,...,...,...,...
981,426-37-3608,Ryley,Kiddell,Male,6645 Goodland Trail,Albany,New York,12232,2.15
990,124-05-3619,Bette-ann,Voaden,Genderfluid,7 Onsgard Alley,Albany,New York,12242,2.88
994,113-81-7717,Dasi,Wainman,Agender,89 Artisan Plaza,Albany,New York,12262,1.93
995,706-55-7345,Athena,Balsdon,Agender,3 Fisk Lane,Albany,New York,12255,3.75
998,560-28-3066,Chicky,Sphinxe,Male,12990 1st Terrace,Albany,New York,12262,2.33

In [40]:
Alb['GPA'].mean()

2.5429047619047607